# robotpkg Makefile for:	wip/eiquadprog
# Created:			Guilhem Saurel on Tue, 17 Sep 2019
#

ORG=			stack-of-tassks
NAME=			eiquadprog
VERSION=		0.0.3

CATEGORIES=		wip
COMMENT=		algorithm of Goldfarb and Idnani for the solution of a QP
LICENSE=		2-clause-bsd
MAINTAINER=		gsaurel@laas.fr

include ../../wip/jrl-cmakemodules/Makefile.common
include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk
include ../../math/eigen3/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
