# robotpkg Makefile for:	wip/py-hpp-universal-robot
# Created:			Guilhem Saurel on Fri, 10 Oct 2018
#

HPP_PACKAGE=		hpp-universal-robot
HPP_COMMENT=		Data specific to robots ur5 and ur10 for hpp-corbaserver
HPP_VERSION=		4.8.1

CATEGORIES=		wip
PYTHON_NOTAG_CONFLICT=	yes

include ../../meta-pkgs/hpp/Makefile.common

include ../../robots/example-robot-data/depend.mk

include ../../mk/language/c.mk
include ../../mk/language/c++11.mk
include ../../mk/robotpkg.mk
