# robotpkg Makefile for:	wip/hrp2-dev
# Created:			Guilhem Saurel on Mon, 9 Oct 2017
#

HRP2_DATE=	20171009
DISTNAME=	hrp2-dev-${HRP2_DATE}

CATEGORIES=	meta-pkgs
COMMENT=	Hrp2 dev Software

META_PACKAGE=	yes

include ../hrp2-14-description/depend.mk
include ../openhrp3-hrp2/depend.mk
include ../../mk/robotpkg.mk
