# robotpkg Makefile for:	wip/py-hpp-environments
# Created:			Guilhem Saurel on Fri, 10 Oct 2018
#

HPP_PACKAGE=		hpp-environments
HPP_COMMENT=		Environments and robot descriptions for HPP

CATEGORIES=		wip

USE_PYTHON=		true
PYTHON_NOTAG_CONFLICT=	yes

include ../../meta-pkgs/hpp/Makefile.common

include ../../mk/language/c.mk
include ../../mk/language/c++11.mk
include ../../mk/robotpkg.mk
