# robotpkg Makefile for:	wip/py27-simple-humanoid-rbprm
# Created:			Guilhem Saurel on Tue, 15 Sep 2020
#

HPP_PACKAGE=	simple-humanoid-rbprm
HPP_COMMENT=	Database for simple-humanoid robot using hpp-rbprm

CATEGORIES=	wip

USE_PYTHON=	true

include ../../meta-pkgs/hpp/Makefile.common

include ../../robots/example-robot-data/depend.mk

include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
