# robotpkg Makefile for:	wip/sot-doc
# Created:			Guilhem Saurel on Fri, 12 Feb 2021
#

ORG=			stack-of-tasks
NAME=			sot-doc
VERSION=		1.1.0

CATEGORIES=		wip
COMMENT=		Documentation entry point for the Stack-Of-Tasks
LICENSE=		2-clause-bsd
MAINTAINER=		gsaurel@laas.fr

include ../../devel/jrl-cmakemodules/Makefile.common
include ../../mk/sysdep/doxygen.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
