# robotpkg Makefile for:	wip/py310-mpc-interface
# Created:			Guilhem Saurel on Wed, 10 Aug 2022
#

ORG=			gepetto
NAME=			mpc-interface
VERSION=		1.0.0
PKGREVISION=		1

USE_PYTHON=		true
DEPEND_ABI.python=	python>=3.6

CATEGORIES=		wip
COMMENT=		A fast and flexible formulation of QP Probl

include ../../devel/jrl-cmakemodules/Makefile.common
include ../../math/eigen3/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/sysdep/doxygen.mk
include ../../mk/sysdep/graphviz.mk
include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
