# robotpkg Makefile for:	wip/sot-hrp2
# Created:			Olivier Stasse, on Wed. 13th January, 2016
#
DISTNAME=		sot-hrp2-1.1.2
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=sot-hrp2/}
MASTER_REPOSITORY=	${MASTER_REPOSITORY_GITHUB}stack-of-tasks/sot-hrp2

CATEGORIES=		wip
COMMENT=		This packages provides a generic Stack Of Tasks library for the humanoid robot HRP-2.
LICENSE=		gnu-lgpl-v3
MAINTAINER=		hpp@laas.fr

DYNAMIC_PLIST_DIRS+=	share/doc/sot-hrp2

include ../../math/hrp2-dynamics/depend.mk
include ../../motion/dynamic-graph-bridge-msgs/depend.mk
include ../../motion/dynamic-graph-bridge/depend.mk
include ../../motion/dynamic-graph/depend.mk
include ../../motion/py-dynamic-graph/depend.mk
include ../../motion/py-sot-tools/depend.mk
include ../../motion/sot-core/depend.mk
include ../../motion/sot-dynamic/depend.mk
include ../../motion/sot-pattern-generator/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../robots/hrp2-14/depend.mk
include ../../robots/hrp2-14/depend.mk
include ../../robots/hrp2-machine/depend.mk
include ../../scripts/py-sot-application/depend.mk
include ../../sysutils/hrp2-bringup/depend.mk
include ../../sysutils/hrp2-computer-monitor/depend.mk
include ../../wip/hrp2-14-description/depend.mk
include ../../wip/sot-dyninv/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/sysdep/doxygen.mk
include ../../mk/sysdep/graphviz.mk
include ../../mk/sysdep/pdflatex.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
