# robotpkg Makefile for:	wip/pyrene-motions
# Created:			Olivier Stasse on Tue, 21 Aug 2018
#

ORG=			pyrene-dev
NAME=			pyrene-motions
VERSION=		1.0.0

CATEGORIES=		wip
COMMENT=		This packages provides motions of the humanoid robot Pyrene readable by the SoT framework.

CMAKE_PREFIX_PATH+=	${PREFIX}

include ../../devel/jrl-cmakemodules/Makefile.common
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
