# robotpkg Makefile for:	wip/hpp-environments
# Created:			Guilhem Saurel on Fri, 10 Oct 2018
#

HPP_PACKAGE=	hpp-environments
HPP_COMMENT=	Environments and robot descriptions for HPP
HPP_VERSION=	4.2.1

CATEGORIES=	wip

DEPEND_ABI.python+=	python<3

include ../../meta-pkgs/hpp/Makefile.common

include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
