# robotpkg Makefile for:	wip/py38-talos-torque-control
# Created:			Guilhem Saurel on Wed, 25 Mar 2020
#

ORG=			stack-of-tasks
NAME=			talos-torque-control
VERSION=		1.1.1

PKGNAME=		${PKGTAG.python-}${DISTNAME}

CATEGORIES=		wip
COMMENT=		Torque control for Talos (python bindings)

CMAKE_ARGS+=		-DINSTALL_DOCUMENTATION=OFF

include ../../devel/jrl-cmakemodules/Makefile.common
include ../../wip/sot-torque-control/depend.mk
include ../../wip/py-sot-torque-control/depend.mk
include ../../graphics/simple-humanoid-description/depend.mk
include ../../graphics/urdfdom/depend.mk
include ../../mapping/octomap/depend.mk
include ../../math/eigen3/depend.mk
include ../../math/pinocchio/depend.mk
include ../../math/py-pinocchio/depend.mk
include ../../optimization/qpoases/depend.mk
include ../../path/hpp-fcl/depend.mk
include ../../path/py-hpp-fcl/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../wip/dynamic-graph-v3/depend.mk
include ../../wip/py-dynamic-graph-v3/depend.mk
include ../../wip/py-sot-core-v3/depend.mk
include ../../optimization/tsid/depend.mk
include ../../optimization/py-tsid/depend.mk
include ../../wip/parametric-curves/depend.mk
include ../../wip/py-parametric-curves/depend.mk
include ../../wip/ddp-actuator-solver/depend.mk
include ../../mk/sysdep/boost-headers.mk
include ../../mk/sysdep/boost-libs.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/sysdep/doxygen.mk
include ../../mk/sysdep/graphviz.mk
include ../../mk/sysdep/py-sphinx.mk
include ../../mk/sysdep/python.mk
include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
