# robotpkg Makefile for:	wip/py37-solo-pybullet
# Created:			Guilhem Saurel on Thu, 17 Oct 2019
#

ORG=			gepetto
NAME=			solo-pybullet
VERSION=		0.1.0

CATEGORIES=		wip
COMMENT=		Simulation and Controller code for Solo Quadruped

LICENSE=		2-clause-bsd
MAINTAINER=		gepetto@laas.fr

USE_PYTHON_ONLY=	true

include ../../devel/jrl-cmakemodules/Makefile.common
include ../../pkgtools/pkg-config/depend.mk
include ../../math/eigen3/depend.mk
include ../../math/py-eigenpy/depend.mk
include ../../math/pinocchio/depend.mk
include ../../math/py-pinocchio/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/sysdep/python.mk
include ../../mk/sysdep/py-numpy.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
