# robotpkg Makefile for:	wip/py-urdf-parser
# Created:			Guilhem Saurel on Wed, 20 Dec 2018
#

ROS_PKG=		urdf_parser_py
ROS_VERSION=	0.4.0

PKGNAME=		${PKGTAG.python-}urdf-parser-${ROS_VERSION}

CATEGORIES=		wip
ROS_COMMENT=	Standalone URDF parser for Python.


include ../../meta-pkgs/ros-base/Makefile.common
include ../../wip/object-recognition-msgs/depend.mk
include ../../wip/octomap-msgs/depend.mk

include ../../devel/ros-catkin/depend.mk
include ../../mk/sysdep/python.mk
include ../../mk/robotpkg.mk
