# robotpkg Makefile for:	wip/py-curves
# Created:			Guilhem Saurel on Wed, 17 Apr 2019
#

ORG=			loco-3d
NAME=			curves
VERSION=		0.2.0

CATEGORIES=		wip
COMMENT=		Library for creating curves

LICENSE=		2-clause-bsd
MAINTAINER=		gepetto@laas.fr

USE_BOOST_LIBS=		python

include ../../devel/jrl-cmakemodules/Makefile.common
include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../math/eigen3/depend.mk
include ../../math/py-eigenpy/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
