# robotpkg Makefile for:	wip/timeoptimization
# Created:			Guilhem Saurel on Wed, 23 Oct 2019
#

ORG=			loco-3d
NAME=			timeoptimization
VERSION=		1.1.0

DISTNAME=		${NAME}-${VERSION}
LICENSE=		gnu-lgpl-v3
CATEGORIES=		wip

HOMEPAGE=		${MASTER_SITE_GITHUB:=${ORG}/${NAME}}
MASTER_REPOSITORY=	${MASTER_REPOSITORY_GITHUB}/${ORG}/${NAME}.git
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=${NAME}/}

include ../../math/eigen3/depend.mk
include ../../devel/yaml-cpp/depend.mk
include ../../devel/ros-catkin/depend.mk
include ../../mk/language/c.mk
include ../../mk/language/c++11.mk
include ../../mk/robotpkg.mk
