# robotpkg Makefile for:	wip/py-hpp-spline
# Created:			Guilhem Saurel on Fri, 10 Oct 2018
#

HPP_PACKAGE=		hpp-spline
HPP_COMMENT=		spline and bezier curves

CATEGORIES=		wip

USE_BOOST_LIBS=		python
PYTHON_NOTAG_CONFLICT=	yes

include ../../meta-pkgs/hpp/Makefile.common

include ../../math/py-eigenpy/depend.mk
include ../../math/eigen3/depend.mk

include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk

include ../../mk/language/c.mk
include ../../mk/language/c++11.mk
include ../../mk/robotpkg.mk
