# robotpkg Makefile for:	wip/talos-dev
# Created:			Guilhem Saurel on Mon, 9 Oct 2017
#

TALOS_DATE=	20171009
DISTNAME=	talos-dev-${TALOS_DATE}

CATEGORIES=	meta-pkgs
COMMENT=	Talos dev Software

META_PACKAGE=	yes

include ../sot-talos/depend.mk
include ../talos-metapkg-ros-control-sot/depend.mk
include ../prf-gazebo-ros-pkgs/depend.mk
include ../talos-simulation/depend.mk
include ../../mk/robotpkg.mk
