# robotpkg Makefile for:	wip/soth
# Created:			Aurelie Clodic on Thu, 30 Oct 2014
#

PKGNAME=		libcdd-${VERSION}
DISTNAME=		libcdd-${VERSION}
VERSION=		0.94.0
PKGREVISION=		1

#MASTER_SITES=		https://www.inf.ethz.ch/personal/fukudak/cdd_home/
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=libcdd/}

MAINTAINER=	hpp@laas.fr
CATEGORIES=	geometry
COMMENT=	Double description for polytope library (in C)
LICENSE=	gnu-gpl


include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/doxygen.mk
include ../../mk/sysdep/autoconf.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
