# robotpkg Makefile for:	devel/infuse-pom-tokamak
# Created:			Quentin Labourey on Wed, 22 Aug 2018
#

NAME=                   infuse-pom-tokamak
VERSION=                0.1
DISTNAME=               ${NAME}-${VERSION}
CATEGORIES=             devel
MASTER_SITES=           http://homepages.laas.fr/qlaboure/infuse/
MASTER_REPOSITORY=      git ssh://git@redmine.laas.fr/laas/users/simon/infuse-pom-base.git
MAINTAINER=             quentin.labourey@laas.fr
HOMEPAGE=               https://redmine.laas.fr/projects/infuse
COMMENT=                Tokamak, pose fuser for the Position Manager
LICENSE=                2-clause-bsd

include ../../wip/infuse-pom-base/depend.mk
include ../../wip/infuse-asn1-types/depend.mk
include ../../wip/infuse-asn1-conversions/depend.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/robotpkg.mk
