# robotpkg Makefile for:	wip/hpp-plot
# Created:			Guilhem Saurel on Tue, 26 Feb 2019
#

HPP_PACKAGE=	hpp-plot
HPP_COMMENT=	Plotting tools for hpp

PKGNAME=		${PKGTAG.qt-}${DISTNAME}

CATEGORIES=		wip

include ../../meta-pkgs/hpp/Makefile.common

include ../../graphics/gepetto-viewer-corba/depend.mk
include ../../path/hpp-corbaserver/depend.mk
include ../../path/hpp-manipulation-corba/depend.mk
include ../../wip/qgv/depend.mk
include ../../mk/sysdep/qt.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
