# robotpkg Makefile for:	wip/py37-talos-rbprm
# Created:			Guilhem Saurel on Wed, 23 Oct 2019
#

HPP_PACKAGE=	talos-rbprm
HPP_COMMENT=	Database for talos robot using hpp-rbprm

CATEGORIES=	wip

USE_PYTHON=	true

include ../../meta-pkgs/hpp/Makefile.common

include ../../robots/example-robot-data/depend.mk

include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
