# robotpkg Makefile for:	wip/py-dynamic-graph-tutorial
# Created:			Guilhem Saurel on Tue, 10 Jul 2018
#

ORG=			stack-of-tasks
NAME=			dynamic-graph-tutorial
VERSION=		1.2.0

CATEGORIES=		wip
COMMENT=		Tutorial for the dynamic-graph
LICENSE=		2-clause-bsd
MAINTAINER=		gepetto-soft@laas.fr

USE_PYTHON_ONLY=	true

include ../../devel/jrl-cmakemodules/Makefile.common
include ../../wip/${NAME}/depend.mk
include ../../wip/dynamic-graph-v3/depend.mk
include ../../wip/py-dynamic-graph-v3/depend.mk
include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
