# robotpkg Makefile for:	interfaces/infuse-idl
# Created:			Ellon Paiva Mendes on Fri,  27 Jul 2018
#

VERSION=		0.1.1
DISTNAME=		infuse-idl-${VERSION}
CATEGORIES=		interfaces
MASTER_SITES=		http://homepages.laas.fr/emendes/infuse/
MASTER_REPOSITORY=	git ssh://git@redmine.laas.fr/laas/users/simon/infuse-idl.git

MAINTAINER=		laas-infuse@laas.fr
COMMENT=		Common IDL interfaces for InFuse genom3 components
LICENSE=		isc

GNU_CONFIGURE=		yes

include ../../interfaces/openrobots-idl/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk
