# robotpkg Makefile for:	interfaces/infuse-msgs-ros
# Created:			Ellon Paiva Mendes on Fri,  27 Jul 2018
#

DISTNAME=		infuse-msgs-ros-0.1.0
CATEGORIES=		interfaces
MASTER_SITES=		http://homepages.laas.fr/emendes/infuse/
MASTER_REPOSITORY=	git ssh://git@redmine.laas.fr/laas/users/simon/infuse-msgs-ros.git

MAINTAINER=		laas-infuse@laas.fr
COMMENT=		Common messages for InFuse ROS-only components
LICENSE=		isc

include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/sysdep/python.mk
include ../../devel/ros-catkin/depend.mk
include ../../interfaces/ros-std-msgs/depend.mk
include ../../lang/ros-message-generation/depend.mk
include ../../lang/ros-message-runtime/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/robotpkg.mk
