# robotpkg Makefile for:	wip/tiago-dev
# Created:			Olivier Stasse on Mon, 6 May 2019
#

TIAGO_DATE=	20190516
DISTNAME=	tiago-dev-${TIAGO_DATE}
PKGREVISION=	1

CATEGORIES=	meta-pkgs
COMMENT=	Tiago dev Software

META_PACKAGE=	yes

include ../../wip/py-sot-tiago/depend.mk
include ../../wip/pal-wsg-gripper/depend.mk
include ../../wip/py-prf-gazebo-ros-pkgs/depend.mk
include ../../wip/tiago-metapkg-ros-control-sot/depend.mk
include ../../wip/tiago-simulation/depend.mk

include ../../mk/robotpkg.mk
