# robotpkg Makefile for:	wip/hpp-rbprm-robot-data
# Created:			Guilhem Saurel on fri, 4 Jan 2019
#

HPP_PACKAGE=	hpp-rbprm-robot-data
HPP_COMMENT=	file database

CATEGORIES=	wip

DEPEND_ABI.python+=	python<3

include ../../meta-pkgs/hpp/Makefile.common

include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
