# robotpkg Makefile for:	wip/hpp-rbprm-robot-data
# Created:			Guilhem Saurel on fri, 4 Jan 2019
#

HPP_PACKAGE=	hpp-rbprm-robot-data
HPP_COMMENT=	file database

CATEGORIES=	wip

USE_PYTHON=	true

include ../../meta-pkgs/hpp/Makefile.common

include ../../mk/language/c.mk
include ../../mk/language/c++11.mk
include ../../mk/robotpkg.mk
