# robotpkg Makefile for:	wip/py36-hpp-hrp2
# Created:			Guilhem Saurel on Tue,  8 Oct 2019
#

HPP_PACKAGE=		hpp-hrp2
HPP_COMMENT=		Data specific to robots hrp2 for hpp-corbaserver
HPP_VERSION=		4.9.0

CATEGORIES=		wip
PYTHON_NOTAG_CONFLICT=	yes

include ../../meta-pkgs/hpp/Makefile.common

include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
