# robotpkg Makefile for:	wip/hpp-affordance
# Created:			Guilhem Saurel on fri, 4 Jan 2019
#

HPP_PACKAGE=	hpp-affordance
HPP_COMMENT=	Extract Whole-Body Affordances for Mutli-Contact Planning.

CATEGORIES=	wip

include ../../meta-pkgs/hpp/Makefile.common

include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk

include ../../math/eigen3/depend.mk
include ../../path/hpp-fcl/depend.mk
include ../../mapping/octomap/depend.mk

include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
