# robotpkg Makefile for:	wip/gazebo-spring
# Created:			Guilhem Saurel on Thu, 19 Nov 2020
#

ORG=			gepetto
NAME=			gazebo-spring
VERSION=		1.0.0
PKGREVISION=		1

CATEGORIES=		wip
COMMENT=		A spring plugin for gazebo
LICENSE=		2-clause-bsd
MAINTAINER=		gsaurel@laas.fr

include ../../devel/jrl-cmakemodules/Makefile.common
include ../../devel/ros-catkin/depend.mk
include ../../devel/ros-roscpp-core
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/sysdep/gazebo.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
