# robotpkg Makefile for:	wip/ros-qualisys
# Created:			Guilhem Saurel on Tue, 19 Jul 2022
#

ORG=			gepetto
NAME=			ros-qualisys
VERSION=		1.0.0

CATEGORIES=		wip
COMMENT=		ROS wrapper for qualisys cpp sdk

include ../../devel/jrl-cmakemodules/Makefile.common

include ../../wip/qualisys-cpp-sdk/depend.mk
include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk
include ../../devel/ros-catkin/depend.mk
include ../../devel/ros-roscpp-core/depend.mk
include ../../interfaces/ros-common-msgs/depend.mk
include ../../math/ros-geometry2/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
