# robotpkg Makefile for:    wip/infuse-envire
# Created:                  Pierre Narvor on Tue, 24 July 2018

DISTNAME=               infuse_envire
CATEGORIES=             devel
VERSION=                0.1
PKGNAME=                infuse-envire
MASTER_SITES=           https://github.com/pnarvor/infuse_envire.git@v${VERSION}
FETCH_METHOD=           git
MASTER_REPOSITORY=      https://github.com/pnarvor/infuse_envire.git
MAINTAINER=             pierre.narvor@laas.fr
HOMEPAGE=               ${MASTER_SITES}
COMMENT=                Minimalist fork of DFKI Envire (build with pure cmake, without autoproj).
LICENSE=                2-clause-bsd



include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/robotpkg.mk

