# robotpkg Makefile for:    wip/infuse-envire
# Created:                  Pierre Narvor on Tue, 24 July 2018

NAME=                   infuse-envire
VERSION=                0.1
DISTNAME=               ${NAME}-${VERSION}
CATEGORIES=             devel
MASTER_SITES=           http://homepages.laas.fr/qlaboure/infuse/
MASTER_REPOSITORY=      git ssh://git@redmine.laas.fr/laas/users/simon/infuse-envire.git
MAINTAINER=             pierre.narvor@laas.fr
HOMEPAGE=               https://redmine.laas.fr/projects/infuse
COMMENT=                Minimalist fork of DFKI Envire (build with pure cmake, without autoproj).
LICENSE=                2-clause-bsd



include ../../math/eigen3/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/robotpkg.mk

