# robotpkg Makefile for:	wip/py27-hyq-rbprm
# Created:			Guilhem Saurel on Tue, 15 Sep 2020
#

HPP_PACKAGE=	hyq-rbprm
HPP_COMMENT=	Database for hyq robot using hpp-rbprm

HPP_VERSION=	4.10.1

CATEGORIES=	wip

USE_PYTHON=	true

include ../../meta-pkgs/hpp/Makefile.common

include ../../robots/example-robot-data/depend.mk

include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
