# robotpkg Makefile for:    wip/infuse-pom-base
# Created:                  Quentin Labourey on Fri, 17 August 2018

NAME=                   infuse-pom-base
VERSION=                0.1
DISTNAME=               ${NAME}-${VERSION}
CATEGORIES=             devel
MASTER_SITES=           http://homepages.laas.fr/qlaboure/infuse/
MASTER_REPOSITORY=      git ssh://git@redmine.laas.fr/laas/users/simon/infuse-pom-base.git
MAINTAINER=             quentin.laboure@laas.fr
HOMEPAGE=               https://redmine.laas.fr/projects/infuse
COMMENT=                Base classes for the Position Manager, PoM
LICENSE=                2-clause-bsd


include ../mk/sysdep/urdfdom.mk
include ../infuse-envire/depend.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/robotpkg.mk
