# robotpkg Makefile for:	wip/sot-talos
# Created:			Olivier Stasse, on Tue. 9th May, 2017
#
DISTNAME=		sot-talos-0.0.4
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=talos/sot-talos/}
MASTER_REPOSITORY=	https://redmine.laas.fr/laas/users/

CATEGORIES=		wip
COMMENT=		This packages provides a generic Stack Of Tasks library for the humanoid robot Pyrene.
LICENSE=		2-clause-bsd
MAINTAINER=		ostasse@laas.fr


include ../../wip/talos-data/depend.mk
include ../../wip/talos-ros-controllers/depend.mk
include ../../wip/talos-metapkg-ros-control-sot/depend.mk
include ../../wip/sot-application-v3/depend.mk
include ../../wip/sot-dyninv-v3/depend.mk
include ../../motion/dynamic-graph-bridge-msgs/depend.mk
include ../../wip/dynamic-graph-bridge-v3/depend.mk
include ../../wip/sot-dynamic-pinocchio-v3/depend.mk
include ../../wip/py-sot-tools-v3/depend.mk
include ../../wip/sot-core-v3/depend.mk
include ../../wip/py-dynamic-graph-v3/depend.mk
include ../../wip/dynamic-graph-v3/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/sysdep/doxygen.mk
include ../../mk/sysdep/graphviz.mk
include ../../mk/sysdep/pdflatex.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk

