
DISTNAME=		rmp400-genom3-0.1.99
CATEGORIES=		robots
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=rmp400/}
MASTER_REPOSITORY=	${MASTER_REPOSITORY_OPENROBOTS}segway-robots/rmp400-genom3

MAINTAINER=		openrobots@laas.fr
COMMENT=		GenoM interface module for the Segway RMP400
LICENSE=		isc

include ../../architecture/genom3/module.mk

include ../../interfaces/openrobots-idl/depend.mk
include ../../hardware/gyro-libs/depend.mk
include ../../robots/rmp-libs/depend.mk
include ../../robots/mana-emergency/depend.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
