# robotpkg Makefile for:	wip/py-sot-talos
# Created:			Olivier Stasse, on Tue. 9th May, 2017
#

ORG=			stack-of-tasks
NAME=			sot-talos
VERSION=		1.3.0

CATEGORIES=		wip
COMMENT=		This packages provides a generic Stack Of Tasks library for the humanoid robot Pyrene.

USE_PYTHON=		true

include ../../devel/jrl-cmakemodules/Makefile.common
include ../../wip/talos-data/depend.mk
include ../../wip/pyrene-motions/depend.mk
include ../../wip/py-sot-application-v3/depend.mk
include ../../motion/dynamic-graph-bridge-msgs/depend.mk
include ../../wip/py-dynamic-graph-bridge-v3/depend.mk
include ../../wip/sot-dynamic-pinocchio-v3/depend.mk
include ../../wip/py-sot-dynamic-pinocchio-v3/depend.mk
include ../../wip/py-sot-tools-v3/depend.mk
include ../../wip/sot-core-v3/depend.mk
include ../../wip/py-sot-core-v3/depend.mk
include ../../wip/py-dynamic-graph-v3/depend.mk
include ../../wip/dynamic-graph-v3/depend.mk
include ../../math/pinocchio/depend.mk
include ../../path/hpp-fcl/depend.mk
include ../../path/py-hpp-fcl/depend.mk
include ../../mapping/octomap/depend.mk
include ../../math/py-pinocchio/depend.mk
include ../../math/py-eigenpy/depend.mk
include ../../math/eigen3/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/sysdep/doxygen.mk
include ../../mk/sysdep/graphviz.mk
include ../../mk/sysdep/pdflatex.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
