# robotpkg Makefile for:	wip/py-hpp-rbprm
# Created:			Guilhem Saurel on Wed, 30 Jan 2019
#

HPP_PACKAGE=		hpp-rbprm
HPP_COMMENT=		RB-PRM planner in HPP
HPP_VERSION=		4.10.1

CATEGORIES=		wip

PYTHON_NOTAG_CONFLICT=	yes

include ../../meta-pkgs/hpp/Makefile.common

include ../../wip/py-anymal-rbprm/depend.mk
include ../../wip/py-hyq-rbprm/depend.mk
include ../../wip/py-simple-humanoid-rbprm/depend.mk
include ../../wip/py-talos-rbprm/depend.mk
include ../../simulation/hpp-environments/depend.mk
include ../../simulation/py-hpp-environments/depend.mk
include ../../math/ndcurves/depend.mk
include ../../math/py-ndcurves/depend.mk

include ../../path/hpp-core/depend.mk
include ../../path/hpp-util/depend.mk
include ../../path/hpp-statistics/depend.mk
include ../../path/hpp-fcl/depend.mk
include ../../path/hpp-constraints/depend.mk
include ../../robots/example-robot-data/depend.mk
include ../../wip/py-hpp-bezier-com-traj/depend.mk
include ../../wip/py-hpp-centroidal-dynamics/depend.mk
include ../../wip/hpp-affordance/depend.mk
include ../../math/pinocchio/depend.mk
include ../../math/hpp-pinocchio/depend.mk
include ../../mapping/octomap/depend.mk

include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk

include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
