# robotpkg Makefile for:    wip/infuse_types_asn1
# Created:                  Quentin Labourey on Fri, 6 July 2018

NAME=                   infuse-asn1-types
VERSION=                0.3
DISTNAME=               ${NAME}-${VERSION}
CATEGORIES=             devel
MASTER_SITES=           http://homepages.laas.fr/qlaboure/infuse/
MASTER_REPOSITORY=      git ssh://git@redmine.laas.fr/laas/users/simon/infuse_asn1_types.git 
MAINTAINER=             quentin.labourey@laas.fr
HOMEPAGE=               https://redmine.laas.fr/projects/infuse
COMMENT=                ASN.1 types for InFuse, compiled in C.
LICENSE=                2-clause-bsd



include ../mk/sysdep/mono.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/robotpkg.mk

