# robotpkg Makefile for:    wip/infuse_types_asn1
# Created:                  Quentin Labourey on Fri, 6 July 2018

DISTNAME=               infuse_asn1_types
CATEGORIES=             devel
VERSION=                0.1
PKGNAME=                infuse-asn1-types
MASTER_SITES=           http://homepages.laas.fr/qlaboure/
MASTER_REPOSITORY=      git https://github.com/QuentinLab/infuse_types_asn1.git
MAINTAINER=             quentin.labourey@laas.fr
HOMEPAGE=               ${MASTER_SITES}
COMMENT=                ASN.1 types for InFuse, compiled in C.
LICENSE=                2-clause-bsd



include ../../mk/sysdep/mono.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/robotpkg.mk

