# robotpkg Makefile for:	devel/infuse-pom-crisp
# Created:			Quentin Labourey on Tue, 21 Aug 2018
#

NAME=                   infuse-pom-crisp
VERSION=                0.1
DISTNAME=               ${NAME}-${VERSION}
PKGREVISION=            1
CATEGORIES=             devel
MASTER_SITES=           http://homepages.laas.fr/qlaboure/infuse/
MASTER_REPOSITORY=      git ssh://git@redmine.laas.fr/laas/users/simon/infuse-pom-crisp.git
MAINTAINER=             quentin.labourey@laas.fr
HOMEPAGE=               https://redmine.laas.fr/projects/infuse
COMMENT=                CRISP: Common Robot Internal State Publisher
LICENSE=                2-clause-bsd


include ../../wip/infuse-envire/depend.mk
include ../../wip/infuse-pom-base/depend.mk
include ../../wip/infuse-asn1-conversions/depend.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/robotpkg.mk
